proxy:
  clientCACertPath: ./sec/clientcacert.pem
  serverCertPath: ./sec/cert.pem
  serverKeyPath: ./sec/key.pem
  addr: ":4000"
  upstreamAddrs: [":4001"]

auth:
  clients:
    - client:
      id: client@client.org
    - client:
      id: client2@client.org
